tap "homebrew/bundle"
tap "homebrew/core"
tap "linuxbrew/xorg"
tap "sanemat/font"
brew "anyenv"
brew "azcopy"
brew "azure-cli"
brew "cmatrix"
brew "gcc"
brew "hugo"
brew "mysql@5.7"
brew "parquet-tools"
brew "ripgrep-all"
brew "sl"
brew "starship"
brew "the_silver_searcher"
brew "xsv"
brew "sanemat/font/ricty", args: ["with-powerline"]
