[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1

#[[plugins]]
#repo = 'Shougo/denite.nvim'


[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python','python3']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python','python3']

#[[plugins]]
#repo = 'andviro/flake8-vim'
#on_ft = ['python','python3']

