
#[[plugins]]
#repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

#Lang

#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = ['python','python3']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python','python3']


#[[plugins]]
#repo = 'andviro/flake8-vim'
#on_ft = ['python','python3']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = ['rust']
[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = ['rust']



