


##

# 設定ファイルをリロードする
bind r source-file ~/.tmux.conf \; display "Reloaded!"


# peneの開始番号
#set-option -g base-index 1

# ウィンドウ履歴の最大行数
set-option -g history-limit 50000

# ペインの移動をvi風にする
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# ペインのリサイズをvi風にする
bind -r C-h resize-pane -L 10
bind -r C-l resize-pane -R 10
bind -r C-j resize-pane -D 10
bind -r C-k resize-pane -U 10

# キーバインド（コピーモード）
bind Space copy-mode
bind p paste-buffer

# 外観
set-option -g default-terminal screen-256color


#
# その他
#

# 下記の設定をしておいたほうがEscの効きがいいらしい
set -s escape-time 0


##
